name: mod_write
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  notus: ^0.1.5
  image_picker: ^0.6.3+4
  #see zefyr_image_delegate_web -> out commented due to cocoapods error
  #image_picker_web: ^0.1.6
  zefyr:
    git:
      url: git://github.com/winwisely99/zefyr.git
      path: packages/zefyr/
  flutter_modular: ^0.5.2
  responsive_scaffold: ^1.3.0+2
  sys_core:
    git:
      url: git://github.com/getcouragenow/core-runtime.git
      path: sys-core/client
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
